=== T0liver/ViNotes/source/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "producer", "year", "grape", "isCuvee", "colour", "sweetness", "country", "region"],
  "properties": {
    "id":                { "type": "string" },
    "name":              { "type": "string" },
    "producer":          { "type": "string" },
    "year":              { "type": "integer", "minimum": 1800, "maximum": 2100 },
    "grape":             { "type": "string" },
    "isCuvee":           { "type": "boolean" },
    "cuveeComponents":   { "type": "array", "items": { "type": "string" } },
    "colour":            { "type": "string", "enum": ["GRAY", "ORANGE", "WHITE", "YELLOW", "ROSE", "SHILLER", "TAWNY", "RED"] },
    "sugar":             { "type": "number", "minimum": 0 },
    "sweetness":         { "type": "string", "enum": ["BRUT_NATURE", "EXTRA_BRUT", "BRUT", "EXTRA_DRY", "DRY", "SEMI_DRY", "SWEET", "UNKNOWN"] },
    "country":           { "type": "string" },
    "region":            { "type": "string" },
    "alcoholPercentage": { "type": "number", "minimum": 0, "maximum": 25 },
    "volume":            { "type": "integer" },
    "description":       { "type": "string" },
    "imageUrl":          { "type": "string" }
  }
}

=== T0liver/ViNotes/source/wines/hungary/sopron.json
[
  {
    "id": "HU-Taschner-2025-Irsai-Oliver",
    "name": "Irsai Olivér",
    "producer": "Taschner borház",
    "year": 2025,
    "grape": "Irsai Olivér",
    "isCuvee": false,
    "colour": "WHITE",
    "sugar": 4.7,
    "sweetness": "DRY",
    "country": "Hungary",
    "region": "Sopron",
    "alcoholPercentage": 11.5,
    "volume": 750,
    "description": "Intenzív aromájú, csupa virág, csupa gyümölcs bor.",
    "imageUrl": "https://vinitaly.winesofhungary.hu/wp-content/uploads/2025/03/taschner_irsai_oliver_2024.png"
  },
  {
    "id": "HU-Taschner-2024-Kekfrankos",
    "name": "Kékfrankos",
    "producer": "Taschner borház",
    "year": 2024,
    "grape": "Kékfrankos",
    "isCuvee": false,
    "colour": "RED",
    "sugar": 4.7,
    "sweetness": "DRY",
    "country": "Hungary",
    "region": "Sopron",
    "alcoholPercentage": 12.5,
    "volume": 750,
    "description": "Intenzív, mély bíbor színű bor, melynek illatában meggyes, málnás, ibolyás és fűszeres, borsos jegyeket fedezhetünk fel.",
    "imageUrl": "https://vinitaly.winesofhungary.hu/wp-content/uploads/2025/03/taschner_irsai_oliver_2024.png"
  }
]
